note_on(0, C3, VELOCITY_DEFAULT)
note_off(1, C3, VELOCITY_OFF)
note_on(2, D3, VELOCITY_DEFAULT)
note_off(3, D3, VELOCITY_OFF)
note_on(4, C3, VELOCITY_DEFAULT)
note_off(5, C3, VELOCITY_OFF)
note_on(6, D3, VELOCITY_DEFAULT)
note_off(7, D3, VELOCITY_OFF)
